### ISSUE TITLE
Memory obfuscation bug

### ISSUE THREAD

**Issue by alepvn33** [security-pride/WASMixer#1]
Hello, I am reporting a small bug when using the memory obfuscation with `obfuscator.memory_obfuscation(key=0)`.
It gives:

> 
> File "WASMixer/obfuscator/core.py", line 420, in memory_encrypten_obfuscation
>     decrypten_load_funcbody = get_decrypten_load()
> NameError: name 'get_decrypten_load' is not defined

This happens because core.py does not import obfuscator/instruction_blocks.py. Adding

`from WASMixer.obfuscator.instruction_blocks import *`

solves the problem. Now, there another error is raised:

> File "WASMixer/obfuscator/core.py", line 461, in memory_encrypten_obfuscation
>     self.wasm_binary.emit_binary(self.wasm_binary.module.path)
> TypeError: ModifyBinary.emit_binary() takes 1 positional argument but 2 were given
> 

this happens because you probably modified the code and forgot to remove the argument inside `self.wasm_binary.emit_binary(`). By removing it, the problem is solved :)

**Comment by abc767234318** [comment]
> Hello, I am reporting a small bug when using the memory obfuscation with `obfuscator.memory_obfuscation(key=0)`. It gives:
> 
> > File "WASMixer/obfuscator/core.py", line 420, in memory_encrypten_obfuscation
> > decrypten_load_funcbody = get_decrypten_load()
> > NameError: name 'get_decrypten_load' is not defined
> 
> This happens because core.py does not import obfuscator/instruction_blocks.py. Adding
> 
> `from WASMixer.obfuscator.instruction_blocks import *`
> 
> solves the problem. Now, there another error is raised:
> 
> > File "WASMixer/obfuscator/core.py", line 461, in memory_encrypten_obfuscation
> > self.wasm_binary.emit_binary(self.wasm_binary.module.path)
> > TypeError: ModifyBinary.emit_binary() takes 1 positional argument but 2 were given
> 
> this happens because you probably modified the code and forgot to remove the argument inside `self.wasm_binary.emit_binary(`). By removing it, the problem is solved :)

Thank you for reporting these issues and providing detailed explanations and solutions. I’m currently working on fixing the code and will push an update as soon as possible. If you encounter any further issues, feel free to reach out to me via my email shangtongcao@bupt.edu.cn.
